<?php
$data = array (
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '食品、饮料、酒水',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '39',
    'name' => '食品、饮料、酒水',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '10',
    'goods_num' => '2',
    'level' => 1,
    'id' => '61',
    'name' => '运动鞋',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '凉鞋/沙滩鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '66',
    'name' => '凉鞋/沙滩鞋',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '运动拖鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '运动拖鞋',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '复古鞋/板鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '复古鞋/板鞋',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '休闲鞋',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '帆布鞋',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '羽毛球鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '羽毛球鞋',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '足球鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '足球鞋',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '跑步鞋',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '全能鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '全能鞋',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '104',
    'name' => '篮球鞋',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '运动服',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '运动服',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '71',
    'name' => 'T恤',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '泳装',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '泳装',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '卫衣',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '运动裤/短裤/裙',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '运动裤/短裤/裙',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '外套',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '运动套装',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '运动套装',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '帽衫',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '帽衫',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '夹克',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '夹克',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '配件/包袋',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '配件/包袋',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '运动包袋',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '运动包袋',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '运动帽',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '运动帽',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '运动配件',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '运动配件',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '运动护具',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '运动护具',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '咖啡机',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '户外用品',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '户外用品',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '户外服装',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '户外服装',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '户外配件',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '户外配件',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '户外鞋',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '户外鞋',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '进口食品、进口牛奶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '进口食品、进口牛奶',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '热门商品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '热门商品',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '17',
    'name' => 'T恤',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '18',
    'name' => '连衣裙',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '雪纺衫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '雪纺衫',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '20',
    'name' => '衬衫',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '雪纺裙',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '雪纺裙',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '外套',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '8',
    'name' => '卫衣',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '小西装',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '9',
    'name' => '小西装',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '夹克衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '10',
    'name' => '夹克衫',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '皮衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '12',
    'name' => '皮衣',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '风衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '13',
    'name' => '风衣',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '短披风',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '14',
    'name' => '短披风',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '短马夹',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '15',
    'name' => '短马夹',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '毛衣',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '毛衣',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '美容化妆、个人护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '美容化妆、个人护理',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '数码相机',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '数码相机',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '便携相机',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '便携相机',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '单反相机',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '单反相机',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '摄像机',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '摄像机',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '索尼',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '30',
    'name' => '索尼',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '佳能',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '佳能',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '松下',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '松下',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '三洋',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '三洋',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '三星',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '三星',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '柯达',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '柯达',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '母婴、玩具音像图书',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '母婴、玩具音像图书',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '电池充电',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '电池充电',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '原装电池',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '原装电池',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '42',
    'name' => '充电器',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '数码伴侣',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '数码伴侣',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '49',
    'name' => '清洁用品',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '照片打印',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '50',
    'name' => '照片打印',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '数码包',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '数码包',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '相机包',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '相机包',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '单反包',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '单反包',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '厨房用品、清洁用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '27',
    'name' => '厨房用品、清洁用品',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '单反镜头',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '单反镜头',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '镜头滤镜',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '镜头滤镜',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '闪光灯/手柄',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '闪光灯/手柄',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '手机通讯、数码电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '手机通讯、数码电器',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '家纺',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '录音笔',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '52',
    'name' => '录音笔',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '苹果配件',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '苹果配件',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '家具',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '耳麦音箱',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '耳麦音箱',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '专业音频',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '专业音频',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '电子词典',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '电子词典',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => '生活用品',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '一体机',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '一体机',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '打印机',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '打印机',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '清洁用品',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '显示器',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '显示器',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '鼠标',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '生活电器、大家电',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '65',
    'name' => '生活电器、大家电',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '按摩器',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '车内饰品',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '车内饰品',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '车载电源',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '车载电源',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '车载按摩器',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '车载按摩器',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '冷暖箱',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '冷暖箱',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '电脑,软件,办公用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '64',
    'name' => '电脑,软件,办公用品',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '81',
    'name' => '剃须刀',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '电吹风',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '剃/脱毛器',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '剃/脱毛器',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '电动牙刷',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '电动牙刷',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '美容美发器',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '美容美发器',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '家居运动、汽车养护',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 0,
    'id' => '58',
    'name' => '家居运动、汽车养护',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '电纸书',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '电纸书',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '麦克风',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '麦克风',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '服装鞋靴、内衣配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '91',
    'name' => '服装鞋靴、内衣配件',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '遥控器',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '遥控器',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '摄影背心',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '摄影背心',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '营养保健、健康器械',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '营养保健、健康器械',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '牛仔裤',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '七分裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '七分裤',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '长裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '长裤',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '热裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '118',
    'name' => '热裤',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '打底裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '打底裤',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '休闲裤',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => '休闲裤',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '钟表珠宝、饰品箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '43',
    'name' => '钟表珠宝、饰品箱包',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '44',
    'name' => '存储卡',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '数码贴膜',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '数码贴膜',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '读卡器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '读卡器',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '三角架/云台',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '三角架/云台',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '机票、健康、礼品卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '105',
    'name' => '机票、健康、礼品卡',
  ),
);
?>